extra_css:
  - style.css
markdown_extensions:
  - smarty
  - toc:
      permalink: true
nav:
  - CHANGES-1.0.0.md
  - CHANGES-2.0.0.md
  - NEWS.md
  - SCHEMAS.md
  - TAGS.md
  - API: $api/comicbox.***
plugins:
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
      css_files:
        - style.css
  - search
  - mkapi
site_author: AJ
site_description: Comicbox Comic Metadata Reader & Writer
site_name: Comicbox
theme:
  color_mode: dark
  name: mkdocs
  strict: true
