comicbox:
  # Options
  comet: True
  comicbookinfo: True
  comicinfoxml: True
  config: null
  delete_orig: False
  delete_tags: False
  dest_path: .
  dry_run: False
  filename: True
  raw: False
  recurse: False
  metadata: {}
  # API Options
  close_fd: True
  check_unrar: True
  # Actions
  cbz: False
  covers: False
  export: False
  file_type: False
  import_fn: null
  index_from: null
  print: False
  rename: False
  version: False
  # Targets
  paths: null
