comicbox:
  # Options
  compute_pages: True
  config: null
  delete: False
  delete_keys: []
  delete_orig: False
  dest_path: .
  dry_run: False
  loglevel: INFO
  metadata: {}
  metadata_cli: null
  read:
    - cli
    - comet
    - metroninfo
    - comicbookinfo
    - comicinfo
    - comictagger
    - filename
    - json
    - pdf
    - yaml
  replace_metadata: False

  read_ignore: []
  recurse: False
  stamp_notes: True
  tagger: null
  # API Options
  close_fd: True
  # Actions
  cbz: False
  cover: False
  export: []
  import_paths: []
  index_from: null
  index_to: null
  print: ""
  rename: False
  write: []
  # Targets
  paths: null
